#!/bin/bash
#Author: Afolabi Rachael
#Program: WinMingle Community C Training
#Description: This is a script that generates the assembly code of a C code and saves it in an output file.

gcc -S $CFILE

